### PR TITLE
fix issue #10 for MAC users

### PR DESCRIPTION
**Pull request by gapp-c**
fixes issue #10

### CODE REVIEW

**Comment by sebastian-zieba** [comment]
Hi Cyril, Thanks for the PR! I'll have a look at it, run the workflow, and merge it to master.

**Comment by sebastian-zieba** [comment]
Looks good to me! That would definitely fix that issue. Thanks!

I think MAC users would also appreciate it if PACMAN would ignore .DS_Store files altogether.
Could you add the following two lines to the end of the "[.gitignore](
https://github.com/sebastian-zieba/PACMAN/blob/master/.gitignore)" file? That would ignore these files in the future when someone does for example "git status".

Just commit and push these changes and I'll approve it :) 

```
# Mac/OSX
.DS_Store
```

**Comment by gapp-c** [comment]
Sure thing! :-)

**Review by sebastian-zieba — APPROVED** [review]
Looking good!

**Comment by sebastian-zieba** [comment]
All tests ran successfully. I'm merging this PR.

**Pull request merged**
